import sys
import os
import time
import glob
import threading
import queue
import re
import ctypes

# -------------------------------------------------------------
# 🛡️ SYSTEM RESOURCE LIMITERS (PREVENTS LAG & FREEZING)
# -------------------------------------------------------------
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# Include root folder in sys.path
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from modules.daemon import HermesDaemon
from ui.dashboard import HermesDashboard
from modules.brain import HermesBrain
from modules.ears import HermesEars
from modules.voice import HermesVoice
from modules.automation import HermesHands
from modules.eyes import HermesEyes
from modules.internet import HermesInternet
from modules.agent import HermesAgent  # ⚡ UNIVERSAL AGENT IMPORTED

# -------------------------------------------------------------
# 🚀 THE COMMAND QUEUE (PREVENTS UI FREEZING & COM ERRORS)
# -------------------------------------------------------------
command_queue = queue.Queue()

def command_worker(app, brain, hands, voice, eyes, internet, agent):
    """Dedicated background worker that executes commands safely."""
    try:
        import pythoncom
        pythoncom.CoInitialize()
    except Exception as e:
        print(f"[COM Warning]: Could not initialize Windows COM bridge: {e}")

    while True:
        cmd = command_queue.get() # Waits patiently for the next command
        if cmd:
            try:
                process_command(cmd, app, brain, hands, voice, eyes, internet, agent)
            except Exception as e:
                app.log(f"[Execution Warning]: {e}")
        command_queue.task_done()

# -------------------------------------------------------------
# 🛡️ ISOLATED SELF-HEALING ERROR CORRECTION WATCHDOG
# -------------------------------------------------------------
def execute_with_self_healing(brain: HermesBrain, app: HermesDashboard, hands: HermesHands, action_type: str, target_val: str, max_retries: int = 2) -> str:
    """Watchdog loop that catches errors and uses direct LLM inference to self-heal parameters."""
    attempt = 0
    current_target = target_val

    while attempt <= max_retries:
        try:
            app.log(f"[Watchdog]: Executing '{action_type}' -> '{current_target}' (Attempt {attempt + 1})")
            result = hands.execute_action(action_type, current_target)
            
            if result and isinstance(result, str) and any(err in result.lower() for err in ["error", "failed", "not found"]):
                raise Exception(result)
                
            return str(result)

        except Exception as e:
            attempt += 1
            error_trace = str(e).strip()
            print(f"[Watchdog Error]: Execution crashed: {error_trace}")
            
            if attempt > max_retries:
                return f"Execution failed permanently after {max_retries} attempts. Error: {error_trace}"

            app.log("[Watchdog]: Error caught. Engaging Self-Healing Protocol...")
            
            # Direct LLM call bypassing planner triggers
            correction = ""
            try:
                if brain.client:
                    messages = [
                        {"role": "system", "content": "You are a strict data-cleaning assistant. Given a failed OS command and its error, output ONLY the corrected target string (e.g. chrome, notepad). No punctuation, no markdown, no code blocks, no explanation."},
                        {"role": "user", "content": f"Action: {action_type}\nFailed Target: {current_target}\nError: {error_trace}"}
                    ]
                    completion = brain.client.chat.completions.create(
                        model=brain.text_model,
                        messages=messages,
                        temperature=0.1,
                        max_tokens=15
                    )
                    correction = completion.choices[0].message.content.strip()
                else:
                    correction = current_target.rstrip('e') # Fallback typo trimmer
            except Exception as llm_err:
                print(f"[Watchdog AI Error]: {llm_err}")
                correction = current_target

            # Aggressive Regex Sanitization to isolate pure app/process names
            words = re.findall(r'[a-zA-Z0-9_\-\.]+', correction)
            if words:
                stopwords = ["success", "output", "chrome", "process", "target", "action", "error", "failed", "not", "found", "process", "named"]
                clean_candidates = [w.lower() for w in words if w.lower() not in stopwords]
                correction = clean_candidates[-1] if clean_candidates else words[-1].lower()
            else:
                correction = current_target

            app.log(f"[Watchdog]: Patch generated by Brain: '{correction}'")
            current_target = correction
            time.sleep(0.5)

# -------------------------------------------------------------
# 🧠 MAIN COMMAND PROCESSOR
# -------------------------------------------------------------
def process_command(cmd: str, app: HermesDashboard, brain: HermesBrain, hands: HermesHands, voice: HermesVoice, eyes: HermesEyes, internet: HermesInternet, agent: HermesAgent):
    cmd_clean = cmd.strip('"\' ')
    if not cmd_clean:
        return

    cmd_lower_raw = cmd_clean.lower()
    for filler in ["hermes,", "hermes", "jarvis,", "jarvis", "please"]:
        if cmd_lower_raw.startswith(filler):
            cmd_clean = cmd_clean[len(filler):].strip()
            break

    cmd_clean = cmd_clean.strip('"\' ,')
    if not cmd_clean:
        return

    response = ""
    app.set_voice_state("PROCESSING", f"PROCESSING: '{cmd_clean.upper()}'")
    app.log(f"[OPERATOR COMMAND]: {cmd_clean}")
    
    cmd_lower = cmd_clean.lower()
    
    # -------------------------------------------------------------
    # ⚡ FAST-TRACK LOCAL OVERRIDES (Zero-Latency OS Controls)
    # -------------------------------------------------------------
    
    # 1. Fast-Track: Opening Apps
    if cmd_lower.startswith("open ") or cmd_lower.startswith("launch "):
        target = cmd_lower.replace("open ", "").replace("launch ", "").strip()
        if "and search" in target or "search for" in target or " and " in target:
            pass  
        else:
            app.log(f"[Fast-Track]: Launching {target}")
            exec_result = execute_with_self_healing(brain, app, hands, "open_app", target)
            print(f"[TRACE]: Fast-Track Hands -> {exec_result}")
            voice.speak(f"Opening {target}, Sir.")
            app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
            return
    
    # Fast-Track: Dynamic Volume Control
    if "volume" in cmd_lower:
        import re
        numbers = re.findall(r'\d+', cmd_lower)
        if numbers:
            target_vol = numbers[0]
            app.log(f"[Fast-Track]: Setting volume to {target_vol}%")
            exec_result = execute_with_self_healing(brain, app, hands, "set_volume", target_vol)
            print(f"[TRACE]: Fast-Track Hands -> {exec_result}")
            voice.speak(f"Volume set to {target_vol} percent, Sir.")
        elif any(k in cmd_lower for k in ["up", "increase", "louder"]):
            execute_with_self_healing(brain, app, hands, "volume_up", "")
            voice.speak("Increasing volume, Sir.")
        elif any(k in cmd_lower for k in ["down", "decrease", "quieter"]):
            execute_with_self_healing(brain, app, hands, "volume_down", "")
            voice.speak("Decreasing volume, Sir.")
        elif "mute" in cmd_lower:
            execute_with_self_healing(brain, app, hands, "mute", "")
            voice.speak("Toggling audio mute, Sir.")
            
        app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
        return
    
    # 2. Fast-Track: Closing Apps & Windows (With Filler Phrase Stripping)
    if cmd_lower.startswith("close ") or cmd_lower.startswith("kill "):
        target = cmd_lower.replace("close ", "").replace("kill ", "").replace(" the ", "").strip()
        
        for wrapper in ["a process named ", "process named ", "named ", "app named ", "program named "]:
            if target.startswith(wrapper):
                target = target[len(wrapper):].strip()

        if target in ["window", "this", "app", "application", "it"]:
            app.log(f"[Fast-Track]: Closing active window")
            exec_result = execute_with_self_healing(brain, app, hands, "close_active_window", "")
        else:
            app.log(f"[Fast-Track]: Terminating {target}")
            exec_result = execute_with_self_healing(brain, app, hands, "kill_process", target)
            
        print(f"[TRACE]: Fast-Track Hands -> {exec_result}")
        voice.speak("Task executed, Sir.")
        app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
        return

    # 3. Fast-Track: Window Resizing
    if cmd_lower.startswith("maximize"):
        execute_with_self_healing(brain, app, hands, "maximize_window", "")
        voice.speak("Maximized, Sir.")
        app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
        return
        
    if cmd_lower.startswith("minimize"):
        execute_with_self_healing(brain, app, hands, "minimize_window", "")
        voice.speak("Minimized, Sir.")
        app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
        return

    # SYSTEM & UI OVERRIDES
    if any(k in cmd_clean.lower() for k in ["shutdown system", "exit hermes", "quit hermes"]):
        voice.speak("Shutting down systems. Goodbye, Sir.")
        os._exit(0)

    if any(k in cmd_clean.lower() for k in ["hide hud", "hide interface", "minimize to tray", "hide dashboard"]):
        app.hide()
        voice.speak("Minimizing interface, Sir. I am still listening in the background.")
        app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
        return

    if any(k in cmd_clean.lower() for k in ["show hud", "open interface", "bring up dashboard", "show dashboard"]):
        app.show()
        app.showFullScreen()
        voice.speak("Restoring visual interface, Sir.")
        app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
        return

    # VISION & LOCAL IMAGE READING OVERRIDES
    cmd_lower_vision = cmd_clean.lower().replace('"', '').replace("'", "")
    vision_triggers = ["look at my screen", "analyze screen", "what is on my screen", "what is there on my screen", "what do you see", "see my screen", "whats on my screen", "what's on my screen"]
    
    if any(k in cmd_lower_vision for k in vision_triggers):
        app.log("[Eyes]: Capturing screen for neural vision analysis...")
        print("\n--- TRACE: VISION SCREEN CAPTURE TRIGGERED ---")
        screen_file = eyes.capture_screen()
        
        if screen_file and os.path.exists(screen_file):
            print(f"[TRACE]: Screenshot captured to '{screen_file}'. Handing to Brain...")
            response = brain.think_with_vision("Analyze what is currently visible on my screen and summarize it for me.", screen_file)
            eyes.cleanup()
        else:
            response = "Sir, screen capture failed."
        
        app.log(f"[HERMES]: {response}")
        app.set_voice_state("SPEAKING", "TRANSMITTING NEURAL SPEECH...")
        voice.speak(response)
        app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
        return

    # Local Image File Reader
    if cmd_lower_vision.startswith("read ") or cmd_lower_vision.startswith("analyze image ") or cmd_lower_vision.startswith("look at image "):
        target_name = cmd_lower_vision.replace("read ", "").replace("analyze image ", "").replace("look at image ", "").strip()
        app.log(f"[Eyes]: Searching local storage for image matching '{target_name}'...")
        
        possible_files = glob.glob(f"*{target_name.replace(' ', '_')}*") + glob.glob(f"*{target_name}*")
        image_file = None
        for f in possible_files:
            if f.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.webp')):
                image_file = f
                break
                
        if not image_file and "test" in target_name:
            for default_name in ["test.png", "test.jpg", "test_image.png", "test_image.jpg"]:
                if os.path.exists(default_name):
                    image_file = default_name
                    break
                
        if image_file and os.path.exists(image_file):
            app.log(f"[TRACE]: Found image file '{image_file}'. Handing to Vision AI...")
            response = brain.think_with_vision(f"Read and extract all text or describe what is visible in this image file: {target_name}", image_file)
        else:
            response = f"Sir, I could not find an image file matching '{target_name}' in the working directory."
            
        app.log(f"[HERMES]: {response}")
        app.set_voice_state("SPEAKING", "TRANSMITTING NEURAL SPEECH...")
        voice.speak(response)
        app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
        return

    # -------------------------------------------------------------
    # 🧠 UNIVERSAL AGENTIC RE-ACT ROUTER (FOR UNRESTRICTED TASKS)
    # -------------------------------------------------------------
    complex_triggers = [
        "organize", "scrape", "write a script", "find and move", 
        "batch rename", "extract text from", "generate a report", "summarize files"
    ]
    
    if any(trigger in cmd_lower for trigger in complex_triggers):
        app.log("[Agent]: Routing request to Universal Autonomous Execution Agent...")
        voice.speak("Synthesizing autonomous execution plan, Sir.")
        
        response = agent.execute_task(cmd_clean)
        
        app.log(f"[HERMES Agent Output]: {response}")
        voice.speak("Autonomous task completed, Sir.")
        app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
        return

    # GENERAL AI BRAIN INGESTION
    if not response:
        response = brain.think(cmd_clean)

    clean_reply = response
    print(f"\n--- TRACE: RAW BRAIN OUTPUT ---\n{response}\n-------------------------------")

    if "COMMAND:" in response:
        try:
            action_types_executed = []
            for line in response.split("\n"):
                if "COMMAND:" in line:
                    print(f"[TRACE]: Parsing line -> {line.strip()}")
                    parts = line.split("COMMAND:")[1].split("|")
                    action_type = parts[0].strip()
                    target_val = ""
                    if len(parts) > 1 and "TARGET:" in parts[1]:
                        target_val = parts[1].split("TARGET:")[1].strip()

                    action_types_executed.append(action_type)
                    app.log(f"[Dispatch]: Action='{action_type}', Target='{target_val}'")
                    print(f"[TRACE]: Successfully Dispatched -> Action: '{action_type}', Target: '{target_val}'")
                    
                    if action_type == "fetch_weather":
                        exec_result = internet.fetch_weather(target_val)
                        app.log(f"[Internet]: {exec_result}")
                        clean_reply = exec_result
                    elif action_type == "fetch_info":
                        exec_result = internet.fetch_wiki(target_val)
                        app.log(f"[Internet]: {exec_result}")
                        clean_reply = exec_result
                    else:
                        print(f"[TRACE]: Handing off to automation.py with Watchdog...")
                        exec_result = execute_with_self_healing(brain, app, hands, action_type, target_val)
                        print(f"[TRACE]: Hands returned -> {exec_result}")
                        app.log(f"[Hands Output]: {exec_result}")

            # CONCISE SPEECH FILTER
            if not any(k in response for k in ["fetch_weather", "fetch_info"]):
                if "open_website" in action_types_executed:
                    clean_reply = "Opening page, Sir."
                elif "type_text" in action_types_executed:
                    clean_reply = "Searching, Sir."
                elif "close_active_window" in action_types_executed or "kill_process" in action_types_executed:
                    clean_reply = "Task executed, Sir."
                else:
                    lines = [l.strip() for l in response.split("\n") if not l.startswith("COMMAND:") and l.strip()]
                    if lines and len(lines[0]) < 60:
                        clean_reply = lines[0]
                    else:
                        clean_reply = "Done, Sir."

        except Exception as e:
            print(f"[TRACE ERROR]: Command parsing failed: {e}")
            app.log(f"[Main Error]: Command parsing failed: {e}")

    app.log(f"[HERMES]: {clean_reply}")
    app.set_voice_state("SPEAKING", "TRANSMITTING NEURAL SPEECH...")
    voice.speak(clean_reply)
    app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")


def background_voice_loop(app, ears, brain, hands, voice, eyes, internet):
    """Listens continuously for direct voice commands."""
    last_speech_time = 0
    while True:
        try:
            if getattr(voice, 'is_speaking', False):
                time.sleep(0.2)
                last_speech_time = time.time()
                continue
            
            if time.time() - last_speech_time < 3.5:
                time.sleep(0.1)
                continue

            app.set_voice_state("LISTENING", "DIRECT LISTENING ACTIVE...")
            voice_cmd = ears.get_command()
            
            if voice_cmd and len(voice_cmd.strip().split()) >= 1:
                clean_cmd = voice_cmd.strip().lower()
                
                echo_phrases = [
                    "acknowledged", "processing command", "sir", "neural speech", 
                    "acknowledged sir", "hermes", "at your service", 
                    "synthesizing autonomous", "execution plan", "autonomous task completed"
                ]
                if any(phrase in clean_cmd for phrase in echo_phrases) and len(clean_cmd.split()) <= 8:
                    time.sleep(0.1)
                    continue

                app.log(f"[Voice Captured]: {voice_cmd}")
                command_queue.put(voice_cmd)
            
            time.sleep(0.1)
        except Exception as e:
            app.log(f"[Voice Loop Error]: {e}")
            time.sleep(0.5)


def main():
    brain = HermesBrain()
    daemon = HermesDaemon()
    daemon.start()
    
    ears = HermesEars()
    voice = HermesVoice()
    hands = HermesHands()
    eyes = HermesEyes()
    internet = HermesInternet()
    agent = HermesAgent(brain) # ⚡ Initialize the Universal Agent

    def handle_gui_command(cmd_text):
        command_queue.put(cmd_text)

    gui = HermesDashboard(command_callback=handle_gui_command)

    # Start the single, hyper-stable worker thread
    worker_thread = threading.Thread(
        target=command_worker,
        args=(gui, brain, hands, voice, eyes, internet, agent), # ⚡ Pass Agent to worker
        daemon=True
    )
    worker_thread.start()

    # Start voice loop
    voice_thread = threading.Thread(
        target=background_voice_loop,
        args=(gui, ears, brain, hands, voice, eyes, internet),
        daemon=True
    )
    voice_thread.start()

    gui.log("[HERMES]: Systems online. Administrator privileges granted.")
    gui.run()


if __name__ == "__main__":
    main()